// <auto-generated />
namespace CourseMessengerWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Courses_AddedField_ShowCourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Courses_AddedField_ShowCourse));
        
        string IMigrationMetadata.Id
        {
            get { return "201501291843547_Courses_AddedField_ShowCourse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
