// <auto-generated />
namespace CourseMessengerWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class LectureHours_added_status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LectureHours_added_status));
        
        string IMigrationMetadata.Id
        {
            get { return "201502131745317_LectureHours_added_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
