// <auto-generated />
namespace CourseMessengerWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Models_Renamed_Reminders_To_ExamTimeTable_Others : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Models_Renamed_Reminders_To_ExamTimeTable_Others));
        
        string IMigrationMetadata.Id
        {
            get { return "201501231730120_Models_Renamed_Reminders_To_ExamTimeTable_Others"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
