// <auto-generated />
namespace CourseMessengerWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class created_LectureHour_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(created_LectureHour_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201502131731372_created_LectureHour_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
